name: storing_data_python
channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.11,<=3.12
  - pandas>=2.0.1
  - treelib
  - sqlalchemy
  - sqlite
  - ipython
  - jupyter
  - flake8
  - pydocstyle
  - black

imports:
  - datro
